# values.yaml
replicaCount: 1

image:
  repository: your_django_image_repository
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

mysql:
  image: mysql:8
  volumeMounts:
    - name: db-data
      mountPath: /var/lib/mysql
    - name: migrate-data
      mountPath: /app/db
