# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: enstitium
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
  selector:
    app: enstitium
