apiVersion: v1
kind: Service
metadata:
  name: enstitium-web-svc
  namespace: enstitium
spec:
  type: NodePort
  selector:
    app: enstitium-web
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31100
  
